name : self-hosted-mac-pro

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  echo-test:
    runs-on: self-hosted
    steps:
      - name: hello world
        run: |
          echo hello world
